name: annamarialambert wedding
favicon: null
layout_spectrum: 0.9153288239613175
typography_spectrum: 0.7378329047933221
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f1f1f1'
    - '#977c73'
    - '#a59b91'
    - '#6c4244'
    - '#3e1c1b'
  brandStrength: 0.5037783728912473
  lightness: 0.5752203369047493
  saturation: 0.9632337472867221
  rhythmicContrast: 0.19488783343695104
purpose: []
