name: annamarialambert wedding
favicon: null
layout_spectrum: 0.74954
typography_spectrum: 0.64873
title: Hand made Wedding Stefana by Anna Maria Lambert
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f1f1f1'
    - '#c2c5bc'
    - '#8b695f'
    - '#724a4a'
    - '#512728'
  brandStrength: 0.1875
  lightness: 0.5625
  saturation: 0.9632337472867221
  rhythmicContrast: 0.19488783343695104
purpose: []
